### ISSUE TITLE
Find a way to properly package GDAL and the RasterTileExtractor on Windows

### ISSUE THREAD

**Issue by kb173** [boku-ilen/geodot-plugin#1]
Currently the RasterTileExtractor library has to be moved to `/usr/lib`, which isn't very portable and practical. Also, GDAL has to be installed.

We need to find a method which is completely portable. Ideally, everything would be in the `bin` folder of the GDNative plugin.

**Comment by kb173** [comment]
With d39f694d61c3561f3ffcaa0a6f3400d9cd8e3ecd, the RasterTileExtractor is properly packaged. Doing the same with GDAL might be more complex - should we just have libgdal-dev as a dependency, like in the landscapelab-server?

**Comment by chrisgraf** [comment]
landscapelab-server just requires libgdal and not libgdal-dev .. what about windows in that case?

**Comment by kb173** [comment]
On Linux, this is done - libgdal.so and libRasterTileExtractor.so can be shipped with libgeodot.so. Unfortunately, I haven't managed to compile it on Windows yet...

**Comment by MathiasBaumgartinger** [comment]
Trying to get this done, my progress so far:

* Download GDAL (this is what i used for windows: https://trac.osgeo.org/osgeo4w/)
* Clone repo
* Build the two Raster- and VectorTileExtractor with cmake from the windows "Developer Command Prompt for Visual Studio 19", you have to have VS downloaded for this
* Follow steps  explained on https://gis.stackexchange.com/questions/150365/sample-for-ms-visual-studio-c-using-gdal-library?answertab=votes#tab-top
  * Open the solutions in VS, include the paths ``path\to\gdal\lib\gdal_i.lib`` in ``Project >Properties > Linker > Input > Additional Dependencies``
  * Also include ``path\to\gdal`` in ``Properties > VC++ Directories`` - ``> Reference Directories`` - ``> Include Directories`` (add include to the path) - ``> Library Directories`` (add lib to the path)

**Comment by MathiasBaumgartinger** [comment]
This will result in being able to include the libraries with ``#include <gdal_priv.h>``.
So I changed  the includes accodingly:
```c++
#include <gdal_priv.h>
#include <gdalwarper.h>
```

**Comment by MathiasBaumgartinger** [comment]
Make sure to run with C++ 17, settings can be found under: ``Project >Properties >C/C++ > Language > C++ Language Standard``

``return (GDALDataset *) GDALOpen(path.c_str(), GA_ReadOnly)`` in RasterTileExtractor.cpp line 236 will not compile. Change to ``return (GDALDataset *) GDALOpen(path.u8string().c_str(), GA_ReadOnly)``.

**Comment by kb173** [comment]
All changes were added, the plugin is now confirmed to compile on both Windows and Linux. The README was updated with detailed instructions in https://github.com/boku-ilen/geodot-plugin/commit/e0f05b0d52829513ba133351966a1ae029a59203, so I'd consider this done!
