### ISSUE TITLE
Problem Launch Demo

### ISSUE THREAD

**Issue by Boyquotes** [boku-ilen/geodot-plugin#19]
I try with godot 3.1 stable ans 3.2 stable and I have these errors : 

Godot Engine v3.1.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
ERROR: set_locale: Unsupported locale 'C', falling back to 'en'.
   At: core/translation.cpp:958.
ERROR: open_dynamic_library: Can't open dynamic library: /media/hacker/data/GODOT/PROJETS/geodot-3.2/demo/addons/geodot/x11/libgeodot.so. Error: /media/hacker/data/GODOT/VERSIONS/31/../lib/libgeodot.so: cannot open shared object file: No such file or directory
   At: drivers/unix/os_unix.cpp:428.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:488.
ERROR: init_library: No nativescript_init in "res://addons/geodot/x11/libgeodot.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1504.
ERROR: start: Script does not inherit a Node: res://addons/geodot/geodot.gdns
   At: main/main.cpp:1557.

**Comment by kb173** [comment]
Hi, thanks for the report! I can see how this isn't clear from the README, but builds are currently not included in the repository. I'm not quite sure how to go about it yet - I noticed that many GDNative libraries do just push their builds into the GitHub repo. Would this be what you'd expect as well? Or would you prefer downloading a zipped release from the GitHub releases? A zipped release would have the benefit that we could directly include some geodata for the demo.

**Comment by kb173** [comment]
Hello again! We decided on pushing the binaries, this was done for Linux with https://github.com/boku-ilen/geodot-plugin/commit/f3dc5c8e19da404d71e5d74a54cce76416f4d989. It should work now - as long as you have some geodata and set the paths accordingly.

**Comment by Boyquotes** [comment]
Thanks for the binaries ;)

But I have another problems with the binaries, (solved : I have link libgdal because the binarie don't find my version : sudo ln -s /usr/lib/libgdal.so.20.5.0 /usr/lib/libgdal.so.26 )

And I will try on Ubuntu 20.04 LTS because on my MX Linux, the glibc version is 2.28, 2.29 required for geodot binaries

+1 A zipped release with a example/pack of TIF file will be great :)

**Comment by kb173** [comment]
For the record: the demo project including Geodot builds and snippets of functional geodata is available in our automated builds now: https://github.com/boku-ilen/geodot-plugin/actions So I think this can be closed.
