### ISSUE TITLE
feature request: get attribute table as a 2d-datatype (eg. list of dict)

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/geodot-plugin#25]
we will need this to get the configuration and any complete dataset (eg. POIs)

**Comment by kb173** [comment]
The base functionality for getting all features, regardless of whether they have geometry or not, was added in 97ae57a and 6dc8a9b. Their attributes can be fetched by name. The only thing left to implement is the function to get all attributes + their values (this was marked as TODO in geodot.cpp).
