### ISSUE TITLE
You can switch to using scons native CompilationDatabase tool and drop scons-compiledb

### ISSUE THREAD

**Issue by bdbaddog** [boku-ilen/geodot-plugin#45]
This was introduced in SCons 4.0.0

https://scons.org/doc/production/HTML/scons-man.html#b-CompilationDatabase

**Comment by kb173** [comment]
Thanks! Done in https://github.com/boku-ilen/geodot-plugin/commit/a47587e174b3a1dea4360382243c4c7586a07c95 - I'm glad we can avoid this dependency.
