### ISSUE TITLE
Mac build broken

### ISSUE THREAD

**Issue by clemens-tolboom** [boku-ilen/geodot-plugin#47]
Commit a47587e174b3a1dea4360382243c4c7586a07c95 broke the build.

```
scons
scons: Reading SConscript files ...
SConsEnvironmentError: No module named compilation_db:
  File "/Users/clemens/Downloads/godot/geodot-plugin/SConstruct", line 9:
    env = DefaultEnvironment(tools=['default', 'compilation_db'])
```

Changing back to the old fixes this for now.
```python
#env = DefaultEnvironment(tools=['default', 'compilation_db'])
env = DefaultEnvironment()
```

### README

Guess we need this requiments somehow documented

**Comment by kb173** [comment]
Ah yes, this requires SCons version 4 or greater. It's been out for half a year, but it seems like many package repositories are still at 3.x :/ I'll surround that with a try/catch
