### ISSUE TITLE
Navigating RasterDemo is little weird

### ISSUE THREAD

**Issue by clemens-tolboom** [boku-ilen/geodot-plugin#53]
Right click release makes scene jump back and more weird mouse rotations

We should add FPS player instead.

**Comment by kb173** [comment]
Oh, strange, I didn't get jumps like that.

I'd like to keep the movement as simple as possible (within one script and one camera node) since it's just for quick demo purposes, but I'm open for PRs to improve it if necessary!

**Comment by clemens-tolboom** [comment]
So we can close this ... I expected auto close due to commit message "Fixes #53" ... not sure why that was not happening.
