### ISSUE TITLE
.a files ends up in osx dir

### ISSUE THREAD

**Issue by clemens-tolboom** [boku-ilen/geodot-plugin#58]
```
scons target=release osgeo_path=/usr/local/Cellar/gdal/3.2.1

find demo/addons/geodot/osx/
demo/addons/geodot/osx/
demo/addons/geodot/osx//libRasterTileExtractor.a <==================
demo/addons/geodot/osx//libgeodot.dylib
demo/addons/geodot/osx//libVectorExtractor.a <===============
```

This is caused by 538e2b3 somehow.

It is a little weird as *libgeodot.dylib* is created OK

**Comment by clemens-tolboom** [comment]
Root cause is we don't have one SConstruct but three. Can we please just have one!

That would prevent future issues like #38 + #43

**Comment by kb173** [comment]
They are explicitly copied at the end of the SConstruct script. However, I rebuilt these libraries to be static, and you're right, it seems like there's actually no need for that copy now.

**Comment by clemens-tolboom** [comment]
.so is shared, .a is static

**Comment by kb173** [comment]
Seems like there may be mac-specific problems with this (further discussion on that in #57), but the .a files were removed from the addon directory in 11c3b21 because that's how it should work (and it does on Linux) - so this can be closed.

**Comment by clemens-tolboom** [comment]
Not sure I agree as in #57 only the `.dylib` version works so I want/need that back right?

**Comment by kb173** [comment]
I'd prefer getting the static library (the `.a`) to work on Mac OS. Not sure what's wrong with it - since it works on Windows and Linux, I'm guessing we're missing some linker flag or something...

**Comment by clemens-tolboom** [comment]
I should have linked to https://github.com/boku-ilen/geodot-plugin/issues/57#issuecomment-779246366 regarding MacOS failing on `.a` file extensions
